### ISSUE TITLE
Continue conversation when LLM responds with question mark doesn't work

### ISSUE THREAD

**Issue by Eitan1112** [jeffc/hassmic#38]
Hello, first of all thanks for putting a great thing out there! I started using it today and it works and it's just really cool, so thank you :)

The issue seems to be that when the LLM responds with a question mark, [it should](https://www.home-assistant.io/blog/2025/04/02/release-20254/#continued-conversation-with-llms) continue listenting after it responds, but instead the satelite service goes idle. I verified it actually ended with a question mark, and it seems a continue_conversation: true attribute also exists.
When I try the same assistant on the companion app it does continue.
It may be related to PR-22, not sure.

Thank you

**Comment by jpbaril** [comment]
BTW, same request as https://github.com/jeffc/hassmic/issues/33

**Comment by TheOddPirate** [comment]
Does this even work with wyoming sattelite?
https://github.com/rhasspy/wyoming-satellite

i dont know if its accurate, but i downloaded this project and asked copilot on help with adding support for continues conversations and it told me this is not implemented in home assistants wyoming integration yet so i needed to wait for it too support it first

**Comment by guttermonk** [comment]
Not sure if this is related or if it's a separate bug, but when I use "Perform action 'Assist satellite: Ask question'" in my automation my Hassmic Wyoming Satellite just responds with "Done". 

When I go to Developer Tools > Actions > assist_satellite.ask_question, the entity dropdown doesn't have my hassmic device listed. In Developer Tools, when I press "Go to YAML mode" and manually input my hassmic assist satellite entity ID:
```
action: assist_satellite.ask_question
data:
  entity_id: assist_satellite.hassmic_wyoming
  question: Test question?
  preannounce: false
  answers:
    - id: "yes"
      sentences:
        - "yes"
    - id: "no"
      sentences:
        - "no"
``` 
I get the following error:
```
Failed to perform the action assist_satellite.ask_question. Unknown error
```
Does hassmic provide the "ask_question" service/action?
